name: app_updater_data
description: Data layer package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_updater_domain:
    path: ../app_updater_domain
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.7.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0

  meta: any
  package_info_plus: ^8.1.0
dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.5.4
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  very_good_analysis: ^6.0.0
